name: PlayerShop
version: 1.1 Beta
description: A simple shop system
main: team.nucodes.playershop.Main
authors: [NuCodes_Team, Vel_Cl]
commands:
    playershop:
        aliases: [pshop, shop, market]
        description: Main command